#blog posts
---
title: "Welcome to my blog"
date: 2019-01-20
---

# meta
theme: minima
title: Halis Şimşek | Github
author: halissimsek
email: info@halissimsek.com.tr
description: > # this means to ignore newlines until "baseurl:"
Halis Şimşek Github Sayfası


# social links
twitter_username: halissimsek44
github_username:  halissimsek

show_excerpts: true # set to false to remove excerpts on the homepage
